/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_1.h"
#include "ADC_DelSig_1.h"
#include "LCD_Char_1.h"
#include "tx_int.h"
#include "rx_int.h"
#include "LED_aliases.h"
#include "LED.h"
#include "Photo_1_aliases.h"
#include "Photo_1.h"
#include "LED_Mode_aliases.h"
#include "LED_Mode.h"
#include "Sw_Mode_aliases.h"
#include "Sw_Mode.h"
#include "Clock_1.h"
#include "Sw_Mode_Int.h"
#include "AMux_1.h"
#include "Pot_aliases.h"
#include "Pot.h"
#include "Photo_2_aliases.h"
#include "Photo_2.h"
#include "Photo_3_aliases.h"
#include "Photo_3.h"
#include "timer_clock.h"
#include "Timer_1.h"
#include "timer_int.h"
#include "PWM_1.h"
#include "pwm_clock.h"
#include "LED_PWM_aliases.h"
#include "LED_PWM.h"
#include "UART_1_IntClock.h"
#include "ADC_DelSig_1_AMux.h"
#include "ADC_DelSig_1_Ext_CP_Clk.h"
#include "ADC_DelSig_1_IRQ.h"
#include "ADC_DelSig_1_theACLK.h"
#include "LCD_Char_1_LCDPort_aliases.h"
#include "LCD_Char_1_LCDPort.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

